USE sunrise_dental_clinic;

-- Staff accounts (one receptionist, one administrator)
-- NOTE: passwords are stored in plain text here to match the level of
-- security taught in this module's lecture material (no hashing library
-- was introduced). See the Task B report, "Limitations and Critical
-- Evaluation", for a discussion of why BCrypt/PBKDF2 hashing should
-- replace this in a production system.
INSERT INTO staff (username, password, full_name, role) VALUES
    ('receptionist1', 'recep123', 'Nadeesha Perera', 'RECEPTIONIST'),
    ('admin1', 'admin123', 'Kasun Fernando', 'ADMINISTRATOR');

-- Treatment types and base costs
INSERT INTO treatment_type (name, base_cost) VALUES
    ('Dental Checkup', 1500.00),
    ('Tooth Filling', 4500.00),
    ('Tooth Extraction', 6000.00),
    ('Root Canal Treatment', 15000.00),
    ('Teeth Cleaning (Scaling)', 3500.00),
    ('Dental Crown', 20000.00),
    ('Braces Consultation', 2500.00);

-- Sample patients
INSERT INTO patient (name, address, contact_number, date_of_birth) VALUES
    ('Amal Silva', '12 Galle Road, Colombo 03', '0771234567', '1990-05-14'),
    ('Nimasha Jayasuriya', '45 Kandy Road, Kadawatha', '0719876543', '1985-11-02'),
    ('Ruwan Dissanayake', '7 Temple Lane, Nugegoda', '0757654321', '1998-02-20');

-- Sample appointments (appointment_number auto-generated by trigger)
INSERT INTO appointment (patient_id, dentist_name, treatment_type_id, appointment_date, appointment_time, registered_by) VALUES
    (1, 'Dr. Chamari Wickramasinghe', 2, CURDATE(), '09:30:00', 1),
    (2, 'Dr. Chamari Wickramasinghe', 4, CURDATE(), '11:00:00', 1),
    (3, 'Dr. Sanjeewa Rathnayake', 5, DATE_ADD(CURDATE(), INTERVAL 1 DAY), '14:00:00', 1);

-- Generate a bill for the first appointment as a worked example
CALL sp_generate_bill('APT-00001', 500.00, @bill_id);
INSERT INTO receipt (bill_id, receipt_number) VALUES (@bill_id, CONCAT('RCP-', LPAD(@bill_id, 5, '0')));
