-- =====================================================================
-- Sunrise Dental Clinic - Appointment & Patient Management System
-- Database schema (MySQL 8.0)
-- Matches the Class Diagram / Data Access Layer (DAO) design from Task A.
-- =====================================================================

DROP DATABASE IF EXISTS sunrise_dental_clinic;
CREATE DATABASE sunrise_dental_clinic CHARACTER SET utf8mb4;
USE sunrise_dental_clinic;

-- ---------------------------------------------------------------------
-- staff : backs StaffUser / Receptionist / Administrator (Actor Hierarchy)
-- role distinguishes the two subclasses from the Class Diagram (Figure 2)
-- ---------------------------------------------------------------------
CREATE TABLE staff (
    staff_id     INT AUTO_INCREMENT PRIMARY KEY,
    username     VARCHAR(50)  NOT NULL UNIQUE,
    password     VARCHAR(100) NOT NULL,
    full_name    VARCHAR(100) NOT NULL,
    role         ENUM('RECEPTIONIST', 'ADMINISTRATOR') NOT NULL DEFAULT 'RECEPTIONIST',
    active       TINYINT(1)   NOT NULL DEFAULT 1,
    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------
-- treatment_type : lookup table for Calculate Treatment Cost use case
-- ---------------------------------------------------------------------
CREATE TABLE treatment_type (
    treatment_type_id INT AUTO_INCREMENT PRIMARY KEY,
    name               VARCHAR(80) NOT NULL UNIQUE,
    base_cost          DECIMAL(10,2) NOT NULL
);

-- ---------------------------------------------------------------------
-- patient : backs the Patient class (Domain Model)
-- patient_id stays the technical primary key (the standard, robust
-- choice for a foreign-key target -- it never changes even if a client
-- gets a new phone number), but contact_number is the patient's
-- practical/business identity: it is UNIQUE here so the database itself
-- guarantees one record per client, matching how
-- DatabaseAppointmentDao.findOrCreatePatient() already looks a patient
-- up by contact_number before creating a new row, so the same client
-- registering for a second visit reuses their existing record and
-- visit history instead of creating a duplicate.
-- ---------------------------------------------------------------------
CREATE TABLE patient (
    patient_id     INT AUTO_INCREMENT PRIMARY KEY,
    name           VARCHAR(100) NOT NULL,
    address        VARCHAR(200) NOT NULL,
    contact_number VARCHAR(20)  NOT NULL UNIQUE,
    date_of_birth  DATE         NULL
);

-- ---------------------------------------------------------------------
-- appointment : backs the Appointment class
-- appointment_number is generated by trg_generate_appointment_number
-- (Assumption A4, Task A) rather than supplied by the client.
-- ---------------------------------------------------------------------
CREATE TABLE appointment (
    appointment_id     INT AUTO_INCREMENT PRIMARY KEY,
    appointment_number VARCHAR(20)  NOT NULL UNIQUE,
    patient_id         INT NOT NULL,
    dentist_name       VARCHAR(100) NOT NULL,
    treatment_type_id  INT NOT NULL,
    appointment_date   DATE NOT NULL,
    appointment_time   TIME NOT NULL,
    status             ENUM('SCHEDULED','COMPLETED','CANCELLED') NOT NULL DEFAULT 'SCHEDULED',
    registered_by      INT NOT NULL,
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id) REFERENCES patient(patient_id),
    CONSTRAINT fk_appointment_treatment FOREIGN KEY (treatment_type_id) REFERENCES treatment_type(treatment_type_id),
    CONSTRAINT fk_appointment_staff FOREIGN KEY (registered_by) REFERENCES staff(staff_id)
);

-- ---------------------------------------------------------------------
-- bill : backs the Bill class. total_amount is populated by the
-- sp_generate_bill stored procedure (business rule: treatment cost +
-- fixed consultation fee), not computed in application code, so the
-- rule lives in one place even if a second client is added later.
-- ---------------------------------------------------------------------
CREATE TABLE bill (
    bill_id           INT AUTO_INCREMENT PRIMARY KEY,
    appointment_id    INT NOT NULL UNIQUE,
    consultation_fee  DECIMAL(10,2) NOT NULL,
    treatment_cost    DECIMAL(10,2) NOT NULL,
    total_amount      DECIMAL(10,2) NOT NULL,
    issue_date        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bill_appointment FOREIGN KEY (appointment_id) REFERENCES appointment(appointment_id)
);

-- ---------------------------------------------------------------------
-- receipt : backs the Receipt class (composed within Bill, 0..1)
-- ---------------------------------------------------------------------
CREATE TABLE receipt (
    receipt_id     INT AUTO_INCREMENT PRIMARY KEY,
    bill_id        INT NOT NULL UNIQUE,
    receipt_number VARCHAR(20) NOT NULL UNIQUE,
    printed_date   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_receipt_bill FOREIGN KEY (bill_id) REFERENCES bill(bill_id)
);

-- =====================================================================
-- Advanced database features (Task B "Excellent" band criterion:
-- "Appropriate use of advanced database features (e.g. stored
-- procedures, functions, triggers to implement business rules)")
-- =====================================================================

-- ---------------------------------------------------------------------
-- Trigger: auto-generate the appointment number on insert, formatted
-- APT-00001, APT-00002, ... This implements Assumption A4 from Task A
-- ("An appointment number is generated automatically by the system")
-- as a database-level business rule, not just in Java.
-- ---------------------------------------------------------------------
DELIMITER $$
CREATE TRIGGER trg_generate_appointment_number
BEFORE INSERT ON appointment
FOR EACH ROW
BEGIN
    DECLARE next_seq INT;
    IF NEW.appointment_number IS NULL OR NEW.appointment_number = '' THEN
        SELECT IFNULL(MAX(appointment_id), 0) + 1 INTO next_seq FROM appointment;
        SET NEW.appointment_number = CONCAT('APT-', LPAD(next_seq, 5, '0'));
    END IF;
END$$
DELIMITER ;

-- ---------------------------------------------------------------------
-- Function: look up the base cost for a treatment type by name.
-- Used by sp_generate_bill and available directly to reporting queries.
-- ---------------------------------------------------------------------
DELIMITER $$
CREATE FUNCTION fn_treatment_base_cost(p_treatment_type_id INT)
RETURNS DECIMAL(10,2)
DETERMINISTIC
READS SQL DATA
BEGIN
    DECLARE v_cost DECIMAL(10,2);
    SELECT base_cost INTO v_cost FROM treatment_type WHERE treatment_type_id = p_treatment_type_id;
    RETURN IFNULL(v_cost, 0.00);
END$$
DELIMITER ;

-- ---------------------------------------------------------------------
-- Stored procedure: generate (or re-fetch) a bill for an appointment.
-- Implements the billing business rule from the assignment brief
-- ("Calculate the total treatment cost based on treatment type and
-- consultation fee") centrally in the database, matching the
-- "Excellent" band's call for stored procedures to implement business
-- rules rather than leaving the calculation only in Java.
-- ---------------------------------------------------------------------
DELIMITER $$
CREATE PROCEDURE sp_generate_bill(
    IN  p_appointment_number VARCHAR(20),
    IN  p_consultation_fee   DECIMAL(10,2),
    OUT p_bill_id            INT
)
BEGIN
    DECLARE v_appointment_id INT;
    DECLARE v_treatment_type_id INT;
    DECLARE v_treatment_cost DECIMAL(10,2);
    DECLARE v_existing_bill_id INT;

    SELECT appointment_id, treatment_type_id
      INTO v_appointment_id, v_treatment_type_id
      FROM appointment
     WHERE appointment_number = p_appointment_number;

    IF v_appointment_id IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Appointment not found';
    END IF;

    SELECT bill_id INTO v_existing_bill_id FROM bill WHERE appointment_id = v_appointment_id LIMIT 1;

    IF v_existing_bill_id IS NOT NULL THEN
        SET p_bill_id = v_existing_bill_id;
    ELSE
        SET v_treatment_cost = fn_treatment_base_cost(v_treatment_type_id);

        INSERT INTO bill (appointment_id, consultation_fee, treatment_cost, total_amount)
        VALUES (v_appointment_id, p_consultation_fee, v_treatment_cost, p_consultation_fee + v_treatment_cost);

        SET p_bill_id = LAST_INSERT_ID();
    END IF;
END$$
DELIMITER ;

-- ---------------------------------------------------------------------
-- Reporting views ("Proposed reports to facilitate decision-making")
-- ---------------------------------------------------------------------
CREATE VIEW v_daily_appointment_report AS
SELECT a.appointment_date,
       COUNT(*)                                  AS total_appointments,
       SUM(a.status = 'COMPLETED')                AS completed,
       SUM(a.status = 'CANCELLED')                AS cancelled,
       SUM(a.status = 'SCHEDULED')                 AS scheduled
FROM appointment a
GROUP BY a.appointment_date
ORDER BY a.appointment_date DESC;

CREATE VIEW v_revenue_report AS
SELECT DATE(b.issue_date) AS bill_date,
       COUNT(*)           AS bills_issued,
       SUM(b.total_amount) AS total_revenue
FROM bill b
GROUP BY DATE(b.issue_date)
ORDER BY bill_date DESC;

CREATE VIEW v_treatment_popularity_report AS
SELECT tt.name AS treatment_type,
       COUNT(a.appointment_id) AS times_booked,
       SUM(CASE WHEN b.bill_id IS NOT NULL THEN b.treatment_cost ELSE 0 END) AS revenue_from_treatment
FROM treatment_type tt
LEFT JOIN appointment a ON a.treatment_type_id = tt.treatment_type_id
LEFT JOIN bill b ON b.appointment_id = a.appointment_id
GROUP BY tt.treatment_type_id, tt.name
ORDER BY times_booked DESC;

-- ---------------------------------------------------------------------
-- Application-level database user (README section 3, step 4).
-- Re-running this script is safe: DROP USER IF EXISTS clears any
-- previous definition before recreating it with the same credentials
-- DatabaseConnectionManager.java is hardcoded to use.
-- ---------------------------------------------------------------------
DROP USER IF EXISTS 'dental_app'@'localhost';
CREATE USER 'dental_app'@'localhost' IDENTIFIED BY 'DentalApp#2026';
GRANT ALL PRIVILEGES ON sunrise_dental_clinic.* TO 'dental_app'@'localhost';
FLUSH PRIVILEGES;
